function EOM = EOM(c,k,l,m,thetadot,theta,x,xdot)
%EOM
%    EOM = EOM(C,K,L,M,THETADOT,THETA,X,XDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Feb-2018 14:15:54

t2 = cos(theta);
t3 = thetadot.^2;
t4 = sin(theta);
t5 = t2.^2;
EOM = [(c.*xdot.*(2.0./3.0)+k.*x.*(2.0./3.0)-k.*t2.*theta.*2.0-c.*l.*t2.*thetadot-l.*m.*t3.*t4.*(2.0./3.0)-m.*t2.*t3.*t4.*xdot)./(m.*(t5-2.0));-(k.*theta.*6.0+c.*l.*thetadot.*3.0-c.*t2.*xdot-k.*t2.*x+m.*t3.*t4.*xdot.*3.0+l.*m.*t2.*t3.*t4)./(l.*m.*2.0-l.*m.*t5)];
