function C = SysDamping(c,l,m,thetadot,theta,xdot)
%SYSDAMPING
%    C = SYSDAMPING(C,L,M,THETADOT,THETA,XDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Feb-2018 14:15:54

t2 = sin(theta);
C = reshape([c,l.*m.*t2.*thetadot.^2,l.*m.*t2.*thetadot.*-2.0,c.*l.^2+l.*m.*t2.*thetadot.*xdot.*2.0],[2,2]);
