function K = SysSpring(k,l,m,thetadot,theta,thetaddot,xddot,xdot)
%SYSSPRING
%    K = SYSSPRING(K,L,M,THETADOT,THETA,THETADDOT,XDDOT,XDOT)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Feb-2018 14:15:54

t2 = sin(theta);
t3 = thetadot.^2;
t4 = cos(theta);
K = reshape([k,0.0,-l.*m.*t3.*t4-l.*m.*t2.*thetaddot,k.*l.*2.0-l.*m.*t2.*xddot+l.*m.*t3.*t4.*xdot],[2,2]);
